server:
  port: 8083


sunshine:
  db:
    database: sunshine_mall_product

spring:
  application:
    name: product-service

feign:
  okhttp:
    enabled: true
  sentinel:
    enabled: true
  seata:
    enabled: false


# 分布式ID配置
distributed-id:
  datacenter-id: 1
  worker-id: 1

rocketmq:
  producer:
    group: product-service-producer-group
