<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    
    <parent>
        <groupId>com.xpcjsu</groupId>
        <artifactId>sunshine-mall-frameworks</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>
    
    <artifactId>sunshine-mall-framework-common</artifactId>
    <name>sunshine-mall-framework-common</name>
    <description>通用工具模块 - 工具类、线程池管理、枚举定义</description>

    <dependencies>
        <dependency>
            <groupId>com.xpcjsu</groupId>
            <artifactId>sunshine-mall-framework-convention</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>com.xpcjsu</groupId>
            <artifactId>sunshine-mall-framework-base</artifactId>
            <version>${project.version}</version>
        </dependency>
        
        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-all</artifactId>
        </dependency>

        
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>

        <!-- RocketMQ 客户端 -->
        <dependency>
            <groupId>org.apache.rocketmq</groupId>
            <artifactId>rocketmq-client</artifactId>
        </dependency>

        <!-- 在 common 模块中编译 Feign 注解接口（不引入 starter，避免自动装配） -->
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-openfeign-core</artifactId>
        </dependency>

        <!--完成SpringMVC自动装配-->
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-webmvc</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>jakarta.servlet</groupId>
            <artifactId>jakarta.servlet-api</artifactId>
            <scope>provided</scope>
        </dependency>

    </dependencies>

</project>
