server:
  port: 8087

feign:
  okhttp:
    enabled: true
  sentinel:
    enabled: true

sunshine:
  db:
    database: sunshine_mall_cart

spring:
  application:
    name: cart-service

rocketmq:
  producer:
    group: cart-service-producer-group

mq:
  enabled: true