server:
  port: 8081

sunshine:
  db:
    database: sunshine_mall_user

spring:
  application:
    name: user-service

feign:
  okhttp:
    enabled: true
  sentinel:
    enabled: true

rocketmq:
  producer:
    group: user-service-producer-group