server:
  port: 8086

hm:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m

  auth:
    exclude-paths:
      - /api/user/login
      - /api/user/register
      - /actuator/health
      - /actuator/info

spring:
  main:
    web-application-type: reactive

