server:
  port: 8080

spring:
  application:
    name: ai-service
  profiles:
    active: dev
    
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        namespace: ${spring.profiles.active}
        group: sunshine-mall
      config:
        namespace: ${spring.profiles.active}
        group: sunshine-mall
        file-extension: yaml

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama3.1
        options:
          temperature: 0.7

logging:
  level:
    com.xpcjsu.sunshinemall: DEBUG
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always